/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#f7bd48',
        'primary-container': '#800020',
        'on-surface-variant': '#584141',
        'on-primary-fixed-variant': '#8e0f28',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf3df',
        'surface-container-high': '#f0e8d4',
        primary: '#570013',
        'surface-container': '#f5edd9',
        'inverse-surface': '#343023',
        'surface-tint': '#af2b3e',
        'surface-variant': '#eae2ce',
        'tertiary-container': '#513900',
        'inverse-on-surface': '#f8f0dc',
        'primary-fixed': '#ffdada',
        secondary: '#4f6073',
        'secondary-fixed': '#d2e4fb',
        'surface-container-highest': '#eae2ce',
        'tertiary-fixed': '#ffdea6',
        'on-error': '#ffffff',
        'on-tertiary-container': '#d59f2b',
        'on-secondary-fixed': '#0b1d2d',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#40000b',
        'surface-bright': '#fff9ee',
        'on-background': '#1f1c0f',
        error: '#ba1a1a',
        surface: '#fff9ee',
        'inverse-primary': '#ffb3b5',
        'surface-dim': '#e1dac6',
        'on-tertiary-fixed-variant': '#5d4200',
        outline: '#8c7071',
        'on-secondary-fixed-variant': '#38485a',
        'outline-variant': '#e0bfbf',
        'secondary-container': '#d2e4fb',
        'primary-fixed-dim': '#ffb3b5',
        'on-secondary': '#ffffff',
        'on-primary-container': '#ff828a',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#b7c8de',
        'on-surface': '#1f1c0f',
        'on-tertiary-fixed': '#271900',
        tertiary: '#362400',
        background: '#fff9ee',
        'on-secondary-container': '#556679',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
