/**
 * Query: produce the full-vault export payload.
 *
 * The payload contains every record the vault owner would need to rebuild
 * their knowledge on another Piper Vault deployment. Derived data (chunks,
 * embeddings) is excluded because it must be regenerated by the destination's
 * ingestion pipeline.
 */
export class ExportVaultQuery {
  constructor(public readonly options: ExportVaultOptions = {}) {}
}

export interface ExportVaultOptions {
  /**
   * When set, limit the export to the given collection. Omit to include every
   * collection the caller can read.
   */
  readonly collectionId?: string;
  /**
   * Whether to include conversation history in the export. Defaults to true.
   */
  readonly includeConversations?: boolean;
}
